### ISSUE TITLE
Consult some solutions

### ISSUE THREAD

**Issue by QQ2287991080** [heldersepu/SwashbuckleTest#2]
Glad to be able to find you such a good swagger test project on GitHub. Currently, I am looking for a way to export swagger documents as office word documents. I don't know if you have explored this aspect.

**Comment by heldersepu** [comment]
No and I don't think that (office word) is a good idea... what's wrong with HTML

**Comment by QQ2287991080** [comment]
It may be that I did not express my thoughts well. My idea is to be able to add a word export function to HTML while maintaining the HTML form of swagger (my current idea is to export word documents through control). Because my team has similar needs.

**Comment by heldersepu** [comment]
This makes absolutely no sense to me... 
this is like asking someone to print a video game because they like it better on paper. 

Swagger-Net provides an interactive documentation for web apis, keyword **web** not offline documents 

If I was in your shoes I would explain the team that if someone wants to look at the documentation they can go to the swagger url, and provide them that ... if they insist I would ask for a big raise and start looking for another job.

**Comment by QQ2287991080** [comment]
Okay, thank you very much for your suggestions.
